# Set cache options
set(${PROJECT_NAME}_BUILD_TESTS OFF CACHE BOOL "Enable tests")
set(${PROJECT_NAME}_BUILD_FUZZER OFF CACHE BOOL "Enable fuzzing")
set(${PROJECT_NAME}_BUILD_BENCHMARKS OFF CACHE BOOL "Enable benchmarks")
set(${PROJECT_NAME}_SANITIZER_ADDRESS OFF CACHE BOOL "Enable ASAN")
set(${PROJECT_NAME}_SANITIZER_MEMORY OFF CACHE BOOL "Enable MSAN, clones and builds custom libc++")
set(${PROJECT_NAME}_SANITIZER_UB OFF CACHE BOOL "Enable UBSAN")
set(${PROJECT_NAME}_COVERAGE_LLVM OFF CACHE BOOL "Enable llvm coverage mapping")
set(${PROJECT_NAME}_COVERAGE_GCOV OFF CACHE BOOL "Enable gcov coverage mapping")
set(${PROJECT_NAME}_USE_LLD OFF CACHE BOOL "Use llvm linker (only with clang)")
